export const congratulationsMessages = [
  'Congratulations!',
  'Well Done!',
  'Great Job!',
  'You Did It!',
  'Awesome!',
  'Amazing!',
  'Fantastic!',
  'Incredible!',
  'Congrats!',
  'Nice Work!',
  'Bravo!',
  'Excellent!',
  'Superb!',
  'Impressive!',
  'Outstanding!',
  'Terrific!',
  'Spectacular!',
  'Phenomenal!',
  'Marvelous!',
  'Splendid!',
  'Magnificent!',
  'Youuuuu did it!',
  'Winner!',
]